version: "3"
services:
  web:
    container_name: slacker-web
    build: .
    ports: 
      - "19002:19002"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true